# Generated by Django 5.0.6 on 2024-06-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_dailyintake_goal_mealplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('group', models.FloatField()),
                ('energ_kal', models.FloatField()),
                ('lipid_tot', models.FloatField()),
                ('carbohydrt', models.FloatField()),
                ('proteina', models.FloatField()),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='dailyintake',
            name='food',
        ),
        migrations.AddField(
            model_name='dailyintake',
            name='food',
            field=models.ManyToManyField(to='accounts.food'),
        ),
    ]
