# Generated by Django 5.0.6 on 2024-06-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_food_remove_dailyintake_food_dailyintake_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyintake',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
