# Generated by Django 5.0.6 on 2024-06-16 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_dailyintake_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='breakfast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakfast_mealplan', to='accounts.food'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='dinner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinner_mealplan', to='accounts.food'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='lunch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_mealplan', to='accounts.food'),
        ),
    ]
