# Generated by Django 5.0.6 on 2024-06-17 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_mealplan_breakfast_alter_mealplan_dinner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='breakfast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakfast_mealplan', to='accounts.dailyintake'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='dinner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinner_mealplan', to='accounts.dailyintake'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='lunch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_mealplan', to='accounts.dailyintake'),
        ),
    ]
